# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('parsed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'received'), (2, b'parsed')], default=1)),
            ],
        ),
    ]
