# from django.test import TestCase
import json
from unittest import TestCase
from django.test.client import RequestFactory
from front_alerts.parsers import GithubRequestEventParser


class PullRequestsEventsTestCase(TestCase):
    def setUp(self):
        self.factory = RequestFactory()
        self.parser = GithubRequestEventParser()
        self.payload = {
            "action": "created",
            "comment": {
                "url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/comments/50482969",
                "id": 50482969,
                "diff_hunk": "@@ -0,0 +1,2 @@\n+just testing",
                "path": "test.txt",
                "position": 1,
                "original_position": 1,
                "commit_id": "38027d31720d76fa8d927d7af8001af478fe1b60",
                "original_commit_id": "38027d31720d76fa8d927d7af8001af478fe1b60",
                "user": {
                    "login": "pleasedontbelong",
                    "id": 1785603,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/pleasedontbelong",
                    "html_url": "https://github.com/pleasedontbelong",
                    "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                    "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                    "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                    "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                    "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                    "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "body": "aure you sure you are just testing?",
                "created_at": "2016-01-21T23:39:58Z",
                "updated_at": "2016-01-21T23:39:58Z",
                "html_url": "https://github.com/pleasedontbelong/front_alerts/pull/9#discussion_r50482969",
                "pull_request_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/9",
                "_links": {
                    "self": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/comments/50482969"
                    },
                    "html": {
                        "href": "https://github.com/pleasedontbelong/front_alerts/pull/9#discussion_r50482969"
                    },
                    "pull_request": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/9"
                    }
                }
            },
            "pull_request": {
                "url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/9",
                "id": 56772671,
                "html_url": "https://github.com/pleasedontbelong/front_alerts/pull/9",
                "diff_url": "https://github.com/pleasedontbelong/front_alerts/pull/9.diff",
                "patch_url": "https://github.com/pleasedontbelong/front_alerts/pull/9.patch",
                "issue_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/9",
                "number": 9,
                "state": "open",
                "locked": False,
                "title": "Test Commit on PR 5",
                "user": {
                    "login": "pleasedontbelong",
                    "id": 1785603,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/pleasedontbelong",
                    "html_url": "https://github.com/pleasedontbelong",
                    "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                    "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                    "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                    "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                    "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                    "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "body": "",
                "created_at": "2016-01-21T16:24:18Z",
                "updated_at": "2016-01-21T23:39:58Z",
                "closed_at": None,
                "merged_at": None,
                "merge_commit_sha": "57666f59c50f247fe1a2d613cad0db05b7e5beb0",
                "assignee": None,
                "milestone": None,
                "commits_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/9/commits",
                "review_comments_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/9/comments",
                "review_comment_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/comments{/number}",
                "comments_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/9/comments",
                "statuses_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/statuses/38027d31720d76fa8d927d7af8001af478fe1b60",
                "head": {
                    "label": "pleasedontbelong:test_hook",
                    "ref": "test_hook",
                    "sha": "38027d31720d76fa8d927d7af8001af478fe1b60",
                    "user": {
                        "login": "pleasedontbelong",
                        "id": 1785603,
                        "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/pleasedontbelong",
                        "html_url": "https://github.com/pleasedontbelong",
                        "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                        "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                        "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                        "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                        "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                        "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                        "type": "User",
                        "site_admin": False
                    },
                    "repo": {
                        "id": 50101950,
                        "name": "front_alerts",
                        "full_name": "pleasedontbelong/front_alerts",
                        "owner": {
                            "login": "pleasedontbelong",
                            "id": 1785603,
                            "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/pleasedontbelong",
                            "html_url": "https://github.com/pleasedontbelong",
                            "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                            "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                            "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                            "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                            "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                            "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                            "type": "User",
                            "site_admin": False
                        },
                        "private": False,
                        "html_url": "https://github.com/pleasedontbelong/front_alerts",
                        "description": "",
                        "fork": False,
                        "url": "https://api.github.com/repos/pleasedontbelong/front_alerts",
                        "forks_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/forks",
                        "keys_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/teams",
                        "hooks_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/hooks",
                        "issue_events_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/events",
                        "assignees_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/tags",
                        "blobs_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/languages",
                        "stargazers_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/stargazers",
                        "contributors_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/contributors",
                        "subscribers_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/subscribers",
                        "subscription_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/subscription",
                        "commits_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/merges",
                        "archive_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/downloads",
                        "issues_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/labels{/name}",
                        "releases_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/deployments",
                        "created_at": "2016-01-21T11:04:20Z",
                        "updated_at": "2016-01-21T11:05:07Z",
                        "pushed_at": "2016-01-21T22:44:38Z",
                        "git_url": "git://github.com/pleasedontbelong/front_alerts.git",
                        "ssh_url": "git@github.com:pleasedontbelong/front_alerts.git",
                        "clone_url": "https://github.com/pleasedontbelong/front_alerts.git",
                        "svn_url": "https://github.com/pleasedontbelong/front_alerts",
                        "homepage": None,
                        "size": 14,
                        "stargazers_count": 0,
                        "watchers_count": 0,
                        "language": "Python",
                        "has_issues": True,
                        "has_downloads": True,
                        "has_wiki": True,
                        "has_pages": False,
                        "forks_count": 0,
                        "mirror_url": None,
                        "open_issues_count": 2,
                        "forks": 0,
                        "open_issues": 2,
                        "watchers": 0,
                        "default_branch": "master"
                    }
                },
                "base": {
                    "label": "pleasedontbelong:master",
                    "ref": "master",
                    "sha": "c221731be2beb00ed3d6800a0b165d548ce00a53",
                    "user": {
                        "login": "pleasedontbelong",
                        "id": 1785603,
                        "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/pleasedontbelong",
                        "html_url": "https://github.com/pleasedontbelong",
                        "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                        "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                        "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                        "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                        "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                        "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                        "type": "User",
                        "site_admin": False
                    },
                    "repo": {
                        "id": 50101950,
                        "name": "front_alerts",
                        "full_name": "pleasedontbelong/front_alerts",
                        "owner": {
                            "login": "pleasedontbelong",
                            "id": 1785603,
                            "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/pleasedontbelong",
                            "html_url": "https://github.com/pleasedontbelong",
                            "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                            "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                            "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                            "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                            "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                            "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                            "type": "User",
                            "site_admin": False
                        },
                        "private": False,
                        "html_url": "https://github.com/pleasedontbelong/front_alerts",
                        "description": "",
                        "fork": False,
                        "url": "https://api.github.com/repos/pleasedontbelong/front_alerts",
                        "forks_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/forks",
                        "keys_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/keys{/key_id}",
                        "collaborators_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/collaborators{/collaborator}",
                        "teams_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/teams",
                        "hooks_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/hooks",
                        "issue_events_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/events{/number}",
                        "events_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/events",
                        "assignees_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/assignees{/user}",
                        "branches_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/branches{/branch}",
                        "tags_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/tags",
                        "blobs_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/blobs{/sha}",
                        "git_tags_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/tags{/sha}",
                        "git_refs_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/refs{/sha}",
                        "trees_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/trees{/sha}",
                        "statuses_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/statuses/{sha}",
                        "languages_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/languages",
                        "stargazers_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/stargazers",
                        "contributors_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/contributors",
                        "subscribers_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/subscribers",
                        "subscription_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/subscription",
                        "commits_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/commits{/sha}",
                        "git_commits_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/commits{/sha}",
                        "comments_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/comments{/number}",
                        "issue_comment_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/comments{/number}",
                        "contents_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/contents/{+path}",
                        "compare_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/compare/{base}...{head}",
                        "merges_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/merges",
                        "archive_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/{archive_format}{/ref}",
                        "downloads_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/downloads",
                        "issues_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues{/number}",
                        "pulls_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls{/number}",
                        "milestones_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/milestones{/number}",
                        "notifications_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/notifications{?since,all,participating}",
                        "labels_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/labels{/name}",
                        "releases_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/releases{/id}",
                        "deployments_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/deployments",
                        "created_at": "2016-01-21T11:04:20Z",
                        "updated_at": "2016-01-21T11:05:07Z",
                        "pushed_at": "2016-01-21T22:44:38Z",
                        "git_url": "git://github.com/pleasedontbelong/front_alerts.git",
                        "ssh_url": "git@github.com:pleasedontbelong/front_alerts.git",
                        "clone_url": "https://github.com/pleasedontbelong/front_alerts.git",
                        "svn_url": "https://github.com/pleasedontbelong/front_alerts",
                        "homepage": None,
                        "size": 14,
                        "stargazers_count": 0,
                        "watchers_count": 0,
                        "language": "Python",
                        "has_issues": True,
                        "has_downloads": True,
                        "has_wiki": True,
                        "has_pages": False,
                        "forks_count": 0,
                        "mirror_url": None,
                        "open_issues_count": 2,
                        "forks": 0,
                        "open_issues": 2,
                        "watchers": 0,
                        "default_branch": "master"
                    }
                },
                "_links": {
                    "self": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/9"
                    },
                    "html": {
                        "href": "https://github.com/pleasedontbelong/front_alerts/pull/9"
                    },
                    "issue": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/9"
                    },
                    "comments": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/9/comments"
                    },
                    "review_comments": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/9/comments"
                    },
                    "review_comment": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/comments{/number}"
                    },
                    "commits": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls/9/commits"
                    },
                    "statuses": {
                        "href": "https://api.github.com/repos/pleasedontbelong/front_alerts/statuses/38027d31720d76fa8d927d7af8001af478fe1b60"
                    }
                }
            },
            "repository": {
                "id": 50101950,
                "name": "front_alerts",
                "full_name": "pleasedontbelong/front_alerts",
                "owner": {
                    "login": "pleasedontbelong",
                    "id": 1785603,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/pleasedontbelong",
                    "html_url": "https://github.com/pleasedontbelong",
                    "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                    "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                    "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                    "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                    "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                    "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "private": False,
                "html_url": "https://github.com/pleasedontbelong/front_alerts",
                "description": "",
                "fork": False,
                "url": "https://api.github.com/repos/pleasedontbelong/front_alerts",
                "forks_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/forks",
                "keys_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/teams",
                "hooks_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/hooks",
                "issue_events_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/events{/number}",
                "events_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/events",
                "assignees_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/assignees{/user}",
                "branches_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/branches{/branch}",
                "tags_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/tags",
                "blobs_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/languages",
                "stargazers_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/stargazers",
                "contributors_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/contributors",
                "subscribers_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/subscribers",
                "subscription_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/subscription",
                "commits_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/contents/{+path}",
                "compare_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/merges",
                "archive_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/downloads",
                "issues_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/issues{/number}",
                "pulls_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/labels{/name}",
                "releases_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/releases{/id}",
                "deployments_url": "https://api.github.com/repos/pleasedontbelong/front_alerts/deployments",
                "created_at": "2016-01-21T11:04:20Z",
                "updated_at": "2016-01-21T11:05:07Z",
                "pushed_at": "2016-01-21T22:44:38Z",
                "git_url": "git://github.com/pleasedontbelong/front_alerts.git",
                "ssh_url": "git@github.com:pleasedontbelong/front_alerts.git",
                "clone_url": "https://github.com/pleasedontbelong/front_alerts.git",
                "svn_url": "https://github.com/pleasedontbelong/front_alerts",
                "homepage": None,
                "size": 14,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "Python",
                "has_issues": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": False,
                "forks_count": 0,
                "mirror_url": None,
                "open_issues_count": 2,
                "forks": 0,
                "open_issues": 2,
                "watchers": 0,
                "default_branch": "master"
            },
            "sender": {
                "login": "pleasedontbelong",
                "id": 1785603,
                "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/pleasedontbelong",
                "html_url": "https://github.com/pleasedontbelong",
                "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                "type": "User",
                "site_admin": False
            }
        }

    def test_opened(self):
        request = self.factory.post(
            '/',
            data=json.dumps(self.payload),
            content_type="application/json",
            HTTP_X_GITHUB_EVENT='pull_request_review_comment')
        self.parser.parse(request)
