# from django.test import TestCase
import json
from unittest import TestCase
from django.test.client import RequestFactory
from front_alerts.parsers import GithubRequestEventParser


class PullRequestsEventsTestCase(TestCase):
    def setUp(self):
        self.factory = RequestFactory()
        self.parser = GithubRequestEventParser()
        self.payload = {
            "action": "created",
            "issue": {
                "url": "https://api.github.com/repos/botify-hq/botify/issues/2457",
                "labels_url": "https://api.github.com/repos/botify-hq/botify/issues/2457/labels{/name}",
                "comments_url": "https://api.github.com/repos/botify-hq/botify/issues/2457/comments",
                "events_url": "https://api.github.com/repos/botify-hq/botify/issues/2457/events",
                "html_url": "https://github.com/botify-hq/botify/pull/2457",
                "id": 127903339,
                "number": 2457,
                "title": "Fix double subscription bug",
                "user": {
                    "login": "AdeleD",
                    "id": 942068,
                    "avatar_url": "https://avatars.githubusercontent.com/u/942068?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/AdeleD",
                    "html_url": "https://github.com/AdeleD",
                    "followers_url": "https://api.github.com/users/AdeleD/followers",
                    "following_url": "https://api.github.com/users/AdeleD/following{/other_user}",
                    "gists_url": "https://api.github.com/users/AdeleD/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/AdeleD/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/AdeleD/subscriptions",
                    "organizations_url": "https://api.github.com/users/AdeleD/orgs",
                    "repos_url": "https://api.github.com/users/AdeleD/repos",
                    "events_url": "https://api.github.com/users/AdeleD/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/AdeleD/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "labels": [
                    {
                        "url": "https://api.github.com/repos/botify-hq/botify/labels/comp:frontend",
                        "name": "comp:frontend",
                        "color": "006b75"
                    },
                    {
                        "url": "https://api.github.com/repos/botify-hq/botify/labels/PR:%20Ready%20for%20review",
                        "name": "PR: Ready for review",
                        "color": "0052cc"
                    }
                ],
                "state": "open",
                "locked": False,
                "assignee": None,
                "milestone": None,
                "comments": 2,
                "created_at": "2016-01-21T11:24:58Z",
                "updated_at": "2016-01-22T09:59:13Z",
                "closed_at": None,
                "pull_request": {
                    "url": "https://api.github.com/repos/botify-hq/botify/pulls/2457",
                    "html_url": "https://github.com/botify-hq/botify/pull/2457",
                    "diff_url": "https://github.com/botify-hq/botify/pull/2457.diff",
                    "patch_url": "https://github.com/botify-hq/botify/pull/2457.patch"
                },
                "body": "Issue: #2237\r\n\r\nIf we can't renew the user's current subscription, we have to close it"
            },
            "comment": {
                "url": "https://api.github.com/repos/botify-hq/botify/issues/comments/173865801",
                "html_url": "https://github.com/botify-hq/botify/pull/2457#issuecomment-173865801",
                "issue_url": "https://api.github.com/repos/botify-hq/botify/issues/2457",
                "id": 173865801,
                "user": {
                    "login": "pleasedontbelong",
                    "id": 1785603,
                    "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/pleasedontbelong",
                    "html_url": "https://github.com/pleasedontbelong",
                    "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                    "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                    "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                    "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                    "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                    "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "created_at": "2016-01-22T09:59:13Z",
                "updated_at": "2016-01-22T09:59:13Z",
                "body": ":+1: "
            },
            "repository": {
                "id": 10640087,
                "name": "botify",
                "full_name": "botify-hq/botify",
                "owner": {
                    "login": "botify-hq",
                    "id": 540514,
                    "avatar_url": "https://avatars.githubusercontent.com/u/540514?v=3",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/botify-hq",
                    "html_url": "https://github.com/botify-hq",
                    "followers_url": "https://api.github.com/users/botify-hq/followers",
                    "following_url": "https://api.github.com/users/botify-hq/following{/other_user}",
                    "gists_url": "https://api.github.com/users/botify-hq/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/botify-hq/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/botify-hq/subscriptions",
                    "organizations_url": "https://api.github.com/users/botify-hq/orgs",
                    "repos_url": "https://api.github.com/users/botify-hq/repos",
                    "events_url": "https://api.github.com/users/botify-hq/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/botify-hq/received_events",
                    "type": "Organization",
                    "site_admin": False
                },
                "private": True,
                "html_url": "https://github.com/botify-hq/botify",
                "description": "Botify Main Repository",
                "fork": False,
                "url": "https://api.github.com/repos/botify-hq/botify",
                "forks_url": "https://api.github.com/repos/botify-hq/botify/forks",
                "keys_url": "https://api.github.com/repos/botify-hq/botify/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/botify-hq/botify/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/botify-hq/botify/teams",
                "hooks_url": "https://api.github.com/repos/botify-hq/botify/hooks",
                "issue_events_url": "https://api.github.com/repos/botify-hq/botify/issues/events{/number}",
                "events_url": "https://api.github.com/repos/botify-hq/botify/events",
                "assignees_url": "https://api.github.com/repos/botify-hq/botify/assignees{/user}",
                "branches_url": "https://api.github.com/repos/botify-hq/botify/branches{/branch}",
                "tags_url": "https://api.github.com/repos/botify-hq/botify/tags",
                "blobs_url": "https://api.github.com/repos/botify-hq/botify/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/botify-hq/botify/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/botify-hq/botify/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/botify-hq/botify/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/botify-hq/botify/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/botify-hq/botify/languages",
                "stargazers_url": "https://api.github.com/repos/botify-hq/botify/stargazers",
                "contributors_url": "https://api.github.com/repos/botify-hq/botify/contributors",
                "subscribers_url": "https://api.github.com/repos/botify-hq/botify/subscribers",
                "subscription_url": "https://api.github.com/repos/botify-hq/botify/subscription",
                "commits_url": "https://api.github.com/repos/botify-hq/botify/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/botify-hq/botify/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/botify-hq/botify/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/botify-hq/botify/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/botify-hq/botify/contents/{+path}",
                "compare_url": "https://api.github.com/repos/botify-hq/botify/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/botify-hq/botify/merges",
                "archive_url": "https://api.github.com/repos/botify-hq/botify/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/botify-hq/botify/downloads",
                "issues_url": "https://api.github.com/repos/botify-hq/botify/issues{/number}",
                "pulls_url": "https://api.github.com/repos/botify-hq/botify/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/botify-hq/botify/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/botify-hq/botify/notifications{?since,all,part}",
                "labels_url": "https://api.github.com/repos/botify-hq/botify/labels{/name}",
                "releases_url": "https://api.github.com/repos/botify-hq/botify/releases{/id}",
                "deployments_url": "https://api.github.com/repos/botify-hq/botify/deployments",
                "created_at": "2013-06-12T09:45:27Z",
                "updated_at": "2016-01-11T17:49:50Z",
                "pushed_at": "2016-01-22T09:38:18Z",
                "git_url": "git://github.com/botify-hq/botify.git",
                "ssh_url": "git@github.com:botify-hq/botify.git",
                "clone_url": "https://github.com/botify-hq/botify.git",
                "svn_url": "https://github.com/botify-hq/botify",
                "homepage": "https://app.botify.com/",
                "size": 76981,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "Python",
                "has_issues": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": False,
                "forks_count": 0,
                "mirror_url": None,
                "open_issues_count": 582,
                "forks": 0,
                "open_issues": 582,
                "watchers": 0,
                "default_branch": "devel"
            },
            "organization": {
                "login": "botify-hq",
                "id": 540514,
                "url": "https://api.github.com/orgs/botify-hq",
                "repos_url": "https://api.github.com/orgs/botify-hq/repos",
                "events_url": "https://api.github.com/orgs/botify-hq/events",
                "members_url": "https://api.github.com/orgs/botify-hq/members{/member}",
                "public_members_url": "https://api.github.com/orgs/botify-hq/public_members{/member}",
                "avatar_url": "https://avatars.githubusercontent.com/u/540514?v=3",
                "description": ""
            },
            "sender": {
                "login": "pleasedontbelong",
                "id": 1785603,
                "avatar_url": "https://avatars.githubusercontent.com/u/1785603?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/pleasedontbelong",
                "html_url": "https://github.com/pleasedontbelong",
                "followers_url": "https://api.github.com/users/pleasedontbelong/followers",
                "following_url": "https://api.github.com/users/pleasedontbelong/following{/other_user}",
                "gists_url": "https://api.github.com/users/pleasedontbelong/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/pleasedontbelong/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/pleasedontbelong/subscriptions",
                "organizations_url": "https://api.github.com/users/pleasedontbelong/orgs",
                "repos_url": "https://api.github.com/users/pleasedontbelong/repos",
                "events_url": "https://api.github.com/users/pleasedontbelong/events{/privacy}",
                "received_events_url": "https://api.github.com/users/pleasedontbelong/received_events",
                "type": "User",
                "site_admin": False
            }
        }

    def test_opened(self):
        # @TODO mock github.get_issue_labels()
        request = self.factory.post(
            '/',
            data=json.dumps(self.payload),
            content_type="application/json",
            HTTP_X_GITHUB_EVENT='issue_comment')
        self.parser.parse(request)
